name: Publish to gh-pages

on:
  push:
    branches:
      - main  # Update to match your branch name (e.g., master or main)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use a recent LTS version (e.g., 16 or 18)

      # Install dependencies
      - run: npm install

      # Build the project
      - run: npm run build

      # Deploy to gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
